// End-to-end interactions on the actual main.py output, with isolated browser storage.
const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url');
const project=path.resolve(__dirname,'../../..'),{chromium}=require(path.join(project,'.test_runtime/node_modules/playwright'));
const out=path.join(project,'.test_outputs/ui_audit_20261002/after');
const base=pathToFileURL(path.join(project,'output_file/鸿蒙智行订单分析汇总.html'));
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',reducedMotion:'reduce'}),checks=[],errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const check=(name,value)=>{assert(value,name);checks.push(name);console.log('PASS',name)};
 const ready=()=>page.waitForFunction(()=>document.querySelector('#page')?.getAttribute('aria-busy')==='false'&&window.DASHBOARD_DATA);
 try{
  const url=new URL(base);url.search=new URLSearchParams({module:'overview',subject:'问界 M9 2026款'});await page.goto(url.href);await ready();
  for(const grain of ['day','week','month']){const button=page.locator('[data-grain="'+grain+'"]');if(await button.isEnabled()){await button.click();await ready();check('切换粒度 '+grain,new URL(page.url()).searchParams.get('grain')===grain)}}
  await page.locator('[data-panel-source]').last().scrollIntoViewIfNeeded();
  const originalScroll=await page.locator('#page').evaluate(n=>n.scrollTop);check('来源入口位于滚动后位置',originalScroll>0);
  await page.locator('[data-panel-source]').last().click();await page.waitForSelector('#rawSearch');
  const sourceFile=await page.locator('#rawFile').inputValue(),sourceSheet=await page.locator('#rawSheet').inputValue();
  await page.goBack();await page.waitForSelector('.kpi');await ready();
  check('从来源返回恢复阅读位置',Math.abs(await page.locator('#page').evaluate(n=>n.scrollTop)-originalScroll)<2);
  await page.goForward();await page.waitForSelector('#rawSearch');
  check('前进恢复来源文件和Sheet',await page.locator('#rawFile').inputValue()===sourceFile&&await page.locator('#rawSheet').inputValue()===sourceSheet);
  await page.locator('#rawSearch').fill('NO_MATCH_UI_AUDIT');await page.reload();await page.waitForSelector('#rawSearch');
  check('底表刷新保留搜索和位置',await page.locator('#rawSearch').inputValue()==='NO_MATCH_UI_AUDIT'&&await page.locator('#rawEmpty').isVisible()&&await page.locator('#rawSheet').inputValue()===sourceSheet);
  await page.locator('#clearRawSearch').click();check('清空底表搜索恢复行',!await page.locator('#rawEmpty').isVisible());
  const download=page.waitForEvent('download');await page.locator('#exportRaw').click();check('底表导出可用',(await download).suggestedFilename().endsWith('.csv'));
  await page.waitForFunction(()=>!document.querySelector('#toast').classList.contains('show'));
  await page.locator('[data-module="sales_forecast"]').click();await page.waitForSelector('.forecast-workspace');await ready();
  check('新模块从顶部开始',await page.locator('#page').evaluate(n=>n.scrollTop)===0);
  await page.locator('[data-forecast-stage-switch="steady"]').click();await page.waitForFunction(()=>document.querySelector('#periodContext').textContent.includes('平销'));
  await page.locator('[data-forecast-stage-switch="launch"]').click();await page.waitForFunction(()=>document.querySelector('#periodContext').textContent==='按预测阶段窗口');
  check('阶段切换同步顶部周期',await page.locator('#periodContext').innerText()==='按预测阶段窗口');
  await page.locator('[data-forecast-tab="evidence"]').click();
  const picker=page.locator('[data-forecast-task="small_progress"] .forecast-chart-picker');
  await picker.locator('summary').click();await picker.locator('[data-reference-search]').fill('M9');
  const visibleNames=await picker.locator('.forecast-chart-options label:visible').allTextContents();
  check('参考搜索筛选代际且保留选中状态',visibleNames.length>0&&visibleNames.every(s=>s.includes('M9')));
  await page.screenshot({path:path.join(out,'reference-picker-1440.png')});
  await page.keyboard.press('Escape');check('Esc关闭并恢复焦点',!await picker.evaluate(n=>n.open)&&await picker.locator('summary').evaluate(n=>n===document.activeElement));
  await picker.locator('summary').click();await picker.locator('[data-reference-search]').fill('NO_MATCH');
  check('参考搜索无结果有恢复提示',await picker.locator('[data-reference-empty]').isVisible());
  await picker.locator('[data-reference-done]').click();check('完成关闭面板',!await picker.evaluate(n=>n.open));
  const chart=page.locator('[data-forecast-task="small_progress"] .forecast-evidence-line-scroll');
  check('每张图仅一个Tab入口',await chart.locator('circle[tabindex="0"]').count()===1);
  await chart.locator('circle[tabindex="0"]').focus();const first=await page.evaluate(()=>document.activeElement.getAttribute('aria-label'));
  await page.keyboard.press('ArrowRight');const second=await page.evaluate(()=>document.activeElement.getAttribute('aria-label'));
  check('方向键读图且精确值可见',first!==second&&(await page.locator('[data-forecast-task="small_progress"] [data-chart-readout]').innerText()).includes(second));
  await page.keyboard.press('Tab');check('Tab直接离开数据点',await page.evaluate(()=>document.activeElement.tagName.toLowerCase()!=='circle'));
  const table=page.locator('[data-forecast-task="small_progress"] [data-forecast-task-chart] .forecast-ref-score-details');await table.locator('summary').click();
  check('数值表固定车型列与日期表头',await table.locator('thead th').last().evaluate(n=>getComputedStyle(n).position)==='sticky'&&await table.locator('tbody th').first().evaluate(n=>getComputedStyle(n).position)==='sticky');
  await page.setViewportSize({width:390,height:844});await picker.locator('summary').click();await picker.locator('[data-reference-search]').fill('M9');await picker.scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(out,'reference-picker-390.png')});
  check('手机参考面板在内容流中',await picker.locator('.forecast-chart-picker-panel').evaluate(n=>getComputedStyle(n).position)==='static');
  check('手机模块列表显示当前模块',await page.locator('#moduleSelect').isVisible()&&await page.locator('#moduleSelect').inputValue()==='sales_forecast'&&!await page.locator('#moduleNav').isVisible());
  await page.locator('#moduleSelect').selectOption('raw');await page.waitForSelector('#rawSearch');check('手机可直接到达底表中心',new URL(page.url()).searchParams.get('module')==='raw');
  await page.locator('#moduleSelect').selectOption('sales_forecast');await page.waitForSelector('.forecast-workspace');
  await page.setViewportSize({width:1440,height:1000});await page.locator('[data-forecast-stage-switch="launch"]').click();await page.locator('[data-forecast-tab="result"]').click();
  const config=await page.locator('.forecast-workspace').evaluate(n=>JSON.parse(n.dataset.forecastConfig));
  const imported=page.locator('[data-forecast-import="launch"]'),date=config.target.launch_date,name=config.target.name;
  const records=()=>page.evaluate(name=>JSON.parse(localStorage.getItem('harmony-forecast-v1:'+location.pathname)).imports.find(row=>row[0]===name)?.[1]?.rows||[],name);
  const snapshot=await page.locator('.forecast-workspace').evaluate(n=>JSON.stringify(n._forecastComparison));
  check('空导入无法重复清除',await imported.locator('[data-forecast-import-clear]').isDisabled());
  await imported.locator('[data-forecast-import-file]').setInputFiles({name:'ui-check.csv',mimeType:'text/csv',buffer:Buffer.from('车型（代际）,日期,预测小订,预测大定\n'+name+','+date+',,123')});
  await page.waitForFunction(()=>document.querySelector('[data-forecast-import="launch"] [data-forecast-import-status]').dataset.state==='success');
  const saved=await records();check('外部预测导入并展示',saved.length===1&&await imported.locator('svg circle[stroke="#7C3AED"]').count()===1);
  await imported.locator('[data-forecast-import-clear]').click();check('清除可撤销',!(await records()).length&&await imported.locator('[data-forecast-import-undo]').isVisible());
  await imported.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'import-undo-1440.png')});
  await imported.locator('[data-forecast-import-undo]').click();assert.deepEqual(await records(),saved);check('撤销恢复全部逐日预测和来源',true);
  await imported.locator('[data-forecast-import-file]').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from('车型（代际）,日期,预测大定\n'+name+','+date+',-1')});
  await page.waitForFunction(()=>document.querySelector('[data-forecast-import="launch"] [data-forecast-import-status]').dataset.state==='error');
  assert.deepEqual(await records(),saved);check('错误导入保留已有数据',true);
  check('导入交互不改变算法预测',snapshot===await page.locator('.forecast-workspace').evaluate(n=>JSON.stringify(n._forecastComparison)));
  await page.locator('[data-forecast-tab="evidence"]').click();await picker.locator('summary').click();
  check('减少动态效果关闭面板动画',await picker.locator('.forecast-chart-picker-panel').evaluate(n=>getComputedStyle(n).animationName)==='none');
  await page.emulateMedia({reducedMotion:'no-preference'});check('普通设置启用短促展开反馈',await picker.locator('.forecast-chart-picker-panel').evaluate(n=>getComputedStyle(n).animationName)==='reference-picker-enter');
  await page.locator('[data-forecast-tab="result"]').click();check('点选面板外自动关闭',!await picker.evaluate(n=>n.open));
  check('无浏览器异常',errors.length===0);
 }finally{await browser.close();fs.writeFileSync(path.join(out,'workflow-report.json'),JSON.stringify({checks,errors},null,2));}
 console.log(JSON.stringify({checks:checks.length,errors}));
})().catch(error=>{console.error(error);process.exitCode=1});
